### ISSUE TITLE
Assignment 2 Brian Medina

### ISSUE THREAD

**Issue by bmedina1977** [bmedina1977/week_02#1]
4b5a5e5

@rharrington31

I struggled a bit with the boxplot question number 7. Made 3 plots.

**Comment by rharrington31** [comment]
Responding in order!

1. Good! You could definitely combine these into one chunk instead of multiple. I normally put all of my `library` calls into one chunk for example.
2. Should have included `summary` as one of the functions to explore your dataset here!
3. Good.
4. This would work, though using `fill = year` would not add anything in this case. Everything is from 2013, so there would be no changes. It would be nice to include at other times, though.
5. I'm not sure what you're looking to accomplish [here](https://github.com/bmedina1977/week_02/blob/4b5a5e5e955266c2bb92c4bc4a6bf6ac88984cb5/Week_02_Assignment.Rmd#L102). The graph would work just fine without adding in the `fill`. In fact, I don't believe the `fill` changes the graph at all.
6. I'm not actually sure what this graph is demonstrating. You simply need to add a `facet_wrap` to what you completed in question 5.
7. I appreciate all of the attempts at this! There's nothing wrong with using the `boxplot` function. This is a base R way of solving this problem, so a bit different than the `ggplot2` method that we talked about in class. Also note that you're comparing it to the wrong variable throughout your attempts - we want to look at `dep_delay` as opposed to `dep_time`. Your last attempt basically gets you there. You wouldn't be able to incorporate `coord_cartesian` with the `boxplot` function - it will only work within `ggplot2`. In order to make this work, you'll need to "add" it to your `ggplot2` code with a `+`. From there, you'd want to play around with what gets you the best view of the graph.
8. Perfectly valid question to ask. I also appreciate that you chose to work with a different dataset. Your graph also seems to answer the question. I may have gone with a question that didn't involve so many `NA` values, though!
9. Great answer!

A couple of general comments. First, I notice that you often use the `#` symbol when you write answers in markdown. No need to do this! In fact, markdown will treat this as a header field when you use the `#` symbol. Second, I'd encourage you to be more descriptive when interpreting the graphs. Look for similarities, differences, or anything notable and describe those things. Assume your reader does not know how to interpret what you've done on their own - it goes a long way!
